### ISSUE TITLE
Going live on fishfight.org domain

### ISSUE THREAD

**Issue by erlend-sh** [fishfight/website#1]
For basic tracking. Most of this will obviously be happening in private so we can exchange the necessary access credentials.

In addition to the default `fishfight.org`, we’ve also got `fishfight.fish` as a backup. I do so badly want to find a legitimate use for that domain as well…

**Comment by dawnlarsson** [comment]
Can you give me Netlify access? it should be a quick setup

**Comment by dawnlarsson** [comment]
Also bind the URLs to the Netlify org in question

**Comment by dawnlarsson** [comment]
(from discord)
we are hosting this via the Amethyst organization in Netlify, this means we can host it for free and easy.

**Comment by dawnlarsson** [comment]
Okay, now it's just a waiting game, the DNS is updated and should go live any second (or hour)
