### ISSUE TITLE
More fish puns

### ISSUE THREAD

**Issue by dawnlarsson** [fishfight/website#2]
Feel free to come up with fish puns I can add to the logo splash, atm we have

- I’m hooked! 
- Seems a bit fishy to me. 
- I’d make him walk the plankton for that.
- Not bad, cod do better… 
- It’s a great oppor-tuna-ty! 
- We whaley need to stop now!

**Comment by erlend-sh** [comment]
I conferred with the punster in the family. She suggested we add these:
- Well, it’s oh-fish-ial.
- Keep your friends close and your anemones closer.
- Let’s just clam down should we.
- Holy shrimp! This scampi happening.
- The new squid on the block.
- I’m so angry I could krill someone.
- Too many fish puns. We should scale back.

**Comment by erlend-sh** [comment]
> cod do better…

Let’s change this to `cod be`? Easier to say.
